In [17]:
import os
import pandas as pd

In [19]:
files = os.listdir("../data")
files

['daily_sales_data_0.csv', 'daily_sales_data_1.csv', 'daily_sales_data_2.csv']

In [20]:
dfs = [] 

for file in files:
    df_temp = pd.read_csv(f"../data/{file}")
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

In [21]:
df.head(10)

          product  price  quantity        date region
0     pink morsel  $3.00       546  2018-02-06  north
1     pink morsel  $3.00       549  2018-02-06  south
2     pink morsel  $3.00       577  2018-02-06   east
3     pink morsel  $3.00       519  2018-02-06   west
4     gold morsel  $9.99       580  2018-02-06  north
5     gold morsel  $9.99       530  2018-02-06  south
6     gold morsel  $9.99       576  2018-02-06   east
7     gold morsel  $9.99       580  2018-02-06   west
8  magenta morsel  $2.50       522  2018-02-06  north
9  magenta morsel  $2.50       560  2018-02-06  south

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41160 entries, 0 to 41159
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   41160 non-null  object
 1   price     41160 non-null  object
 2   quantity  41160 non-null  int64
 3   date      41160 non-null  object
 4   region    41160 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.6+ MB

In [27]:
df['product'].unique()

array(['pink morsel', 'gold morsel', 'magenta morsel',
       'chartreuse morsel', 'periwinkle morsel', 'vermilion morsel',
       'lapis morsel'], dtype=object)

In [28]:
df["price"] = df["price"].str.replace("$", "", regex=False).astype(float)

In [33]:
df = df[df["product"] == "pink morsel"].copy()

In [34]:
df["sales"] = df["price"] * df["quantity"]

In [31]:
df.head()

        product  price  quantity        date region   sales
0   pink morsel    3.0       546  2018-02-06  north  1638.0
1   pink morsel    3.0       549  2018-02-06  south  1647.0
2   pink morsel    3.0       577  2018-02-06   east  1731.0
3   pink morsel    3.0       519  2018-02-06   west  1557.0
28  pink morsel    3.0       529  2018-02-07  north  1587.0

In [32]:
df.dtypes

product      object
price       float64
quantity      int64
date         object
region       object
sales       float64
dtype: object

In [35]:
df = df[["sales", "date", "region"]]

In [36]:
df.head()

     sales        date region
0   1638.0  2018-02-06  north
1   1647.0  2018-02-06  south
2   1731.0  2018-02-06   east
3   1557.0  2018-02-06   west
28  1587.0  2018-02-07  north

In [37]:
df.shape

(5880, 3)

In [38]:
df.isnull().sum()

sales     0
date      0
region    0
dtype: int64

In [39]:
df.to_csv("../data/processed_data.csv", index=False)